# Generated by Django 5.0.6 on 2024-07-20 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=10, unique=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('tailored_video', models.FileField(blank=True, null=True, upload_to='tailored_videos/')),
                ('s3_download_link', models.URLField(blank=True, max_length=500, null=True)),
                ('metadata_link', models.URLField(blank=True, max_length=500, null=True)),
                ('expires_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('request_payment', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment_link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_info', to='files_app.fileupload')),
            ],
        ),
    ]
